//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootball.Common.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchsAction
    {
        public int Id { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<int> PlayerId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
