//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootball.Common.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInTeam
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int UsersTeamId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual UsersTeam UsersTeam { get; set; }
    }
}
