//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootball.Common.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTeam
    {
        public UsersTeam()
        {
            this.PlayerInTeam = new HashSet<PlayerInTeam>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LeagueId { get; set; }
    
        public virtual League League { get; set; }
        public virtual ICollection<PlayerInTeam> PlayerInTeam { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
